//! Arrow kernel-based filter expression operator.
//!
//! Provides a predicate DSL (`col`, `lit`, comparisons, boolean logic) that
//! evaluates directly against Arrow arrays using `arrow::compute` kernels.
//! The result is a `BooleanArray` applied as a selection vector — zero-copy.
//!
//! Two spellings are available for building predicates:
//!
//! - Stringly-typed: [`col`] plus one of the `lit_*` constructors. The column
//!   name and the literal type are both unchecked until the batch is evaluated.
//! - Typed: [`Col<T>`] handles generated by `#[derive(RheiSchema)]`, reached
//!   through the generated `col()` accessor (`Sensor::col().value().gt(20.0)`).
//!   Column names come from the schema and literals are checked at compile time.

use std::fmt;
use std::marker::PhantomData;
use std::sync::Arc;

use arrow_array::cast::AsArray;
use arrow_array::types::{
    Float32Type, Float64Type, Int8Type, Int16Type, Int32Type, Int64Type, UInt8Type, UInt16Type,
    UInt32Type, UInt64Type,
};
use arrow_array::{Array, BooleanArray, RecordBatch, StringArray};
use arrow_schema::DataType;
use async_trait::async_trait;

use crate::arrow::{BufferOutput, OperatorContext, RheiBuffer, RheiSchema, StreamFunction};

/// A scalar value for comparison predicates.
#[derive(Clone, Debug)]
pub enum ScalarValue {
    /// 64-bit signed integer.
    Int64(i64),
    /// 64-bit unsigned integer.
    UInt64(u64),
    /// 64-bit floating point.
    Float64(f64),
    /// UTF-8 string.
    Utf8(String),
    /// Boolean.
    Bool(bool),
}

/// A predicate expression that evaluates against a `RecordBatch`.
#[derive(Clone, Debug)]
pub enum Expr {
    /// Reference to a named column.
    Column(String),
    /// A literal scalar value.
    Literal(ScalarValue),
    /// Greater than comparison.
    Gt(Box<Expr>, Box<Expr>),
    /// Greater than or equal comparison.
    GtEq(Box<Expr>, Box<Expr>),
    /// Less than comparison.
    Lt(Box<Expr>, Box<Expr>),
    /// Less than or equal comparison.
    LtEq(Box<Expr>, Box<Expr>),
    /// Equality comparison.
    Eq(Box<Expr>, Box<Expr>),
    /// Inequality comparison.
    NotEq(Box<Expr>, Box<Expr>),
    /// Logical AND of two boolean expressions.
    And(Box<Expr>, Box<Expr>),
    /// Logical OR of two boolean expressions.
    Or(Box<Expr>, Box<Expr>),
    /// Logical NOT of a boolean expression.
    Not(Box<Expr>),
    /// True for rows where the inner expression is null.
    IsNull(Box<Expr>),
    /// True for rows where the inner expression is non-null.
    IsNotNull(Box<Expr>),
}

/// Creates a column reference expression.
pub fn col(name: impl Into<String>) -> Expr {
    Expr::Column(name.into())
}

/// Creates a literal i64 expression.
pub fn lit_i64(v: i64) -> Expr {
    Expr::Literal(ScalarValue::Int64(v))
}

/// Creates a literal u64 expression.
pub fn lit_u64(v: u64) -> Expr {
    Expr::Literal(ScalarValue::UInt64(v))
}

/// Creates a literal f64 expression.
pub fn lit_f64(v: f64) -> Expr {
    Expr::Literal(ScalarValue::Float64(v))
}

/// Creates a literal string expression.
pub fn lit_str(v: impl Into<String>) -> Expr {
    Expr::Literal(ScalarValue::Utf8(v.into()))
}

/// Creates a literal bool expression.
pub fn lit_bool(v: bool) -> Expr {
    Expr::Literal(ScalarValue::Bool(v))
}

impl Expr {
    /// Greater than comparison.
    pub fn gt(self, other: Expr) -> Expr {
        Expr::Gt(Box::new(self), Box::new(other))
    }

    /// Greater than or equal comparison.
    pub fn gt_eq(self, other: Expr) -> Expr {
        Expr::GtEq(Box::new(self), Box::new(other))
    }

    /// Less than comparison.
    pub fn lt(self, other: Expr) -> Expr {
        Expr::Lt(Box::new(self), Box::new(other))
    }

    /// Less than or equal comparison.
    pub fn lt_eq(self, other: Expr) -> Expr {
        Expr::LtEq(Box::new(self), Box::new(other))
    }

    /// Equality comparison.
    pub fn eq(self, other: Expr) -> Expr {
        Expr::Eq(Box::new(self), Box::new(other))
    }

    /// Inequality comparison.
    pub fn not_eq(self, other: Expr) -> Expr {
        Expr::NotEq(Box::new(self), Box::new(other))
    }

    /// Logical AND.
    pub fn and(self, other: Expr) -> Expr {
        Expr::And(Box::new(self), Box::new(other))
    }

    /// Logical OR.
    pub fn or(self, other: Expr) -> Expr {
        Expr::Or(Box::new(self), Box::new(other))
    }

    /// Logical NOT.
    #[allow(clippy::should_implement_trait)]
    pub fn negate(self) -> Expr {
        Expr::Not(Box::new(self))
    }

    /// True for rows where this expression is null.
    pub fn is_null(self) -> Expr {
        Expr::IsNull(Box::new(self))
    }

    /// True for rows where this expression is non-null.
    pub fn is_not_null(self) -> Expr {
        Expr::IsNotNull(Box::new(self))
    }
}

impl ScalarValue {
    /// Returns the value as a wide integer, if it is an integral literal.
    ///
    /// Floating point, string, and boolean literals return `None` rather than
    /// silently truncating.
    fn as_i128(&self) -> Option<i128> {
        match self {
            Self::Int64(v) => Some(i128::from(*v)),
            Self::UInt64(v) => Some(i128::from(*v)),
            Self::Float64(_) | Self::Utf8(_) | Self::Bool(_) => None,
        }
    }

    /// Returns the value as `f64`, if it is a numeric literal.
    #[allow(clippy::cast_precision_loss)]
    fn as_f64(&self) -> Option<f64> {
        match self {
            Self::Int64(v) => Some(*v as f64),
            Self::UInt64(v) => Some(*v as f64),
            Self::Float64(v) => Some(*v),
            Self::Utf8(_) | Self::Bool(_) => None,
        }
    }
}

/// Rust types that can be used as a literal in a typed [`Col`] comparison.
///
/// Narrow integers widen to `Int64`/`UInt64` and `f32` widens to `Float64`;
/// the comparison kernel narrows the literal back to the column's Arrow type
/// when the predicate is evaluated.
pub trait ScalarLike: Sized {
    /// Converts this value into a [`ScalarValue`] literal.
    fn into_scalar_value(self) -> ScalarValue;
}

macro_rules! impl_scalar_like {
    ($($ty:ty => $variant:ident),* $(,)?) => {
        $(
            impl ScalarLike for $ty {
                fn into_scalar_value(self) -> ScalarValue {
                    ScalarValue::$variant(self.into())
                }
            }
        )*
    };
}

impl_scalar_like! {
    i8 => Int64,
    i16 => Int64,
    i32 => Int64,
    i64 => Int64,
    u8 => UInt64,
    u16 => UInt64,
    u32 => UInt64,
    u64 => UInt64,
    f32 => Float64,
    f64 => Float64,
    bool => Bool,
    String => Utf8,
}

/// A typed handle to a named column.
///
/// `Col<T>` pairs a column name with the Rust type of that column, so
/// comparisons take ordinary Rust values instead of hand-built literals. The
/// `#[derive(RheiSchema)]` macro generates one accessor per field, reached
/// through the generated `col()` associated function:
///
/// ```ignore
/// // not-compiled: illustrative, requires a derived schema in scope
/// stream.filter(Sensor::col().value().gt(20.0).and(Sensor::col().name().eq("a")))
/// ```
///
/// Columns whose type has no scalar representation (lists, binary) still get a
/// handle, but only the name/null predicates are available on it.
pub struct Col<T> {
    name: &'static str,
    _marker: PhantomData<fn() -> T>,
}

impl<T> Clone for Col<T> {
    fn clone(&self) -> Self {
        *self
    }
}

impl<T> Copy for Col<T> {}

impl<T> fmt::Debug for Col<T> {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        f.debug_tuple("Col").field(&self.name).finish()
    }
}

impl<T> Col<T> {
    /// Creates a typed column handle for `name`.
    ///
    /// Normally called by `#[derive(RheiSchema)]` rather than by hand.
    #[must_use]
    pub const fn new(name: &'static str) -> Self {
        Self {
            name,
            _marker: PhantomData,
        }
    }

    /// Returns the column name.
    #[must_use]
    pub const fn name(&self) -> &'static str {
        self.name
    }

    /// Returns this column as an untyped [`Expr`].
    #[must_use]
    pub fn expr(&self) -> Expr {
        Expr::Column(self.name.to_string())
    }

    /// True for rows where this column is null.
    #[must_use]
    pub fn is_null(&self) -> Expr {
        self.expr().is_null()
    }

    /// True for rows where this column is non-null.
    #[must_use]
    pub fn is_not_null(&self) -> Expr {
        self.expr().is_not_null()
    }
}

impl<T> From<Col<T>> for Expr {
    fn from(c: Col<T>) -> Expr {
        c.expr()
    }
}

impl<T: ScalarLike> Col<T> {
    fn cmp(&self, value: impl Into<T>, op: fn(Expr, Expr) -> Expr) -> Expr {
        op(self.expr(), Expr::Literal(value.into().into_scalar_value()))
    }

    /// Greater than comparison against a literal.
    #[must_use]
    pub fn gt(&self, value: impl Into<T>) -> Expr {
        self.cmp(value, Expr::gt)
    }

    /// Greater than or equal comparison against a literal.
    #[must_use]
    pub fn gt_eq(&self, value: impl Into<T>) -> Expr {
        self.cmp(value, Expr::gt_eq)
    }

    /// Less than comparison against a literal.
    #[must_use]
    pub fn lt(&self, value: impl Into<T>) -> Expr {
        self.cmp(value, Expr::lt)
    }

    /// Less than or equal comparison against a literal.
    #[must_use]
    pub fn lt_eq(&self, value: impl Into<T>) -> Expr {
        self.cmp(value, Expr::lt_eq)
    }

    /// Equality comparison against a literal.
    #[must_use]
    #[allow(clippy::should_implement_trait)]
    pub fn eq(&self, value: impl Into<T>) -> Expr {
        self.cmp(value, Expr::eq)
    }

    /// Inequality comparison against a literal.
    #[must_use]
    pub fn not_eq(&self, value: impl Into<T>) -> Expr {
        self.cmp(value, Expr::not_eq)
    }

    /// Inclusive range check: `low <= column <= high`.
    #[must_use]
    pub fn between(&self, low: impl Into<T>, high: impl Into<T>) -> Expr {
        self.gt_eq(low).and(self.lt_eq(high))
    }

    /// Membership test, expanded into a chain of equality comparisons.
    ///
    /// An empty set of values yields a predicate that matches no rows.
    #[must_use]
    pub fn is_in<V: Into<T>>(&self, values: impl IntoIterator<Item = V>) -> Expr {
        values
            .into_iter()
            .map(|v| self.eq(v))
            .reduce(Expr::or)
            .unwrap_or(Expr::Literal(ScalarValue::Bool(false)))
    }
}

/// Internal enum for intermediate evaluation results.
enum EvalResult {
    Array(Arc<dyn Array>),
    Scalar(ScalarValue),
}

fn evaluate(expr: &Expr, batch: &RecordBatch) -> anyhow::Result<EvalResult> {
    match expr {
        Expr::Column(name) => {
            let idx = batch.schema().index_of(name)?;
            Ok(EvalResult::Array(Arc::clone(batch.column(idx))))
        }
        Expr::Literal(v) => Ok(EvalResult::Scalar(v.clone())),
        Expr::Gt(lhs, rhs) => eval_cmp(lhs, rhs, batch, CmpOp::Gt),
        Expr::GtEq(lhs, rhs) => eval_cmp(lhs, rhs, batch, CmpOp::GtEq),
        Expr::Lt(lhs, rhs) => eval_cmp(lhs, rhs, batch, CmpOp::Lt),
        Expr::LtEq(lhs, rhs) => eval_cmp(lhs, rhs, batch, CmpOp::LtEq),
        Expr::Eq(lhs, rhs) => eval_cmp(lhs, rhs, batch, CmpOp::Eq),
        Expr::NotEq(lhs, rhs) => eval_cmp(lhs, rhs, batch, CmpOp::NotEq),
        Expr::And(lhs, rhs) => {
            let l = evaluate_to_bool(lhs, batch)?;
            let r = evaluate_to_bool(rhs, batch)?;
            Ok(EvalResult::Array(Arc::new(
                arrow::compute::kernels::boolean::and(&l, &r)?,
            )))
        }
        Expr::Or(lhs, rhs) => {
            let l = evaluate_to_bool(lhs, batch)?;
            let r = evaluate_to_bool(rhs, batch)?;
            Ok(EvalResult::Array(Arc::new(
                arrow::compute::kernels::boolean::or(&l, &r)?,
            )))
        }
        Expr::Not(inner) => {
            let b = evaluate_to_bool(inner, batch)?;
            Ok(EvalResult::Array(Arc::new(
                arrow::compute::kernels::boolean::not(&b)?,
            )))
        }
        Expr::IsNull(inner) => {
            let arr = evaluate_to_array(inner, batch)?;
            Ok(EvalResult::Array(Arc::new(
                arrow::compute::kernels::boolean::is_null(arr.as_ref())?,
            )))
        }
        Expr::IsNotNull(inner) => {
            let arr = evaluate_to_array(inner, batch)?;
            Ok(EvalResult::Array(Arc::new(
                arrow::compute::kernels::boolean::is_not_null(arr.as_ref())?,
            )))
        }
    }
}

fn evaluate_to_array(expr: &Expr, batch: &RecordBatch) -> anyhow::Result<Arc<dyn Array>> {
    match evaluate(expr, batch)? {
        EvalResult::Array(arr) => Ok(arr),
        EvalResult::Scalar(_) => Err(anyhow::anyhow!(
            "null checks require a column, not a literal"
        )),
    }
}

fn evaluate_to_bool(expr: &Expr, batch: &RecordBatch) -> anyhow::Result<BooleanArray> {
    let result = evaluate(expr, batch)?;
    match result {
        EvalResult::Array(arr) => arr
            .as_any()
            .downcast_ref::<BooleanArray>()
            .cloned()
            .ok_or_else(|| anyhow::anyhow!("expression did not produce BooleanArray")),
        EvalResult::Scalar(ScalarValue::Bool(v)) => {
            Ok(BooleanArray::from(vec![v; batch.num_rows()]))
        }
        EvalResult::Scalar(_) => Err(anyhow::anyhow!("expected boolean expression")),
    }
}

#[derive(Clone, Copy)]
enum CmpOp {
    Gt,
    GtEq,
    Lt,
    LtEq,
    Eq,
    NotEq,
}

fn eval_cmp(lhs: &Expr, rhs: &Expr, batch: &RecordBatch, op: CmpOp) -> anyhow::Result<EvalResult> {
    let left = evaluate(lhs, batch)?;
    let right = evaluate(rhs, batch)?;

    let result = match (left, right) {
        (EvalResult::Array(arr), EvalResult::Scalar(scalar)) => {
            cmp_array_scalar(&arr, &scalar, op)?
        }
        (EvalResult::Scalar(scalar), EvalResult::Array(arr)) => {
            cmp_array_scalar(&arr, &scalar, flip_op(op))?
        }
        (EvalResult::Array(l), EvalResult::Array(r)) => cmp_array_array(&l, &r, op)?,
        (EvalResult::Scalar(_), EvalResult::Scalar(_)) => {
            anyhow::bail!("cannot compare two literals")
        }
    };
    Ok(EvalResult::Array(Arc::new(result)))
}

fn flip_op(op: CmpOp) -> CmpOp {
    match op {
        CmpOp::Gt => CmpOp::Lt,
        CmpOp::GtEq => CmpOp::LtEq,
        CmpOp::Lt => CmpOp::Gt,
        CmpOp::LtEq => CmpOp::GtEq,
        CmpOp::Eq => CmpOp::Eq,
        CmpOp::NotEq => CmpOp::NotEq,
    }
}

/// Applies `op` to a pair of Arrow `Datum`s.
macro_rules! apply_cmp {
    ($lhs:expr, $rhs:expr, $op:expr) => {{
        use arrow::compute::kernels::cmp;
        match $op {
            CmpOp::Gt => cmp::gt($lhs, $rhs)?,
            CmpOp::GtEq => cmp::gt_eq($lhs, $rhs)?,
            CmpOp::Lt => cmp::lt($lhs, $rhs)?,
            CmpOp::LtEq => cmp::lt_eq($lhs, $rhs)?,
            CmpOp::Eq => cmp::eq($lhs, $rhs)?,
            CmpOp::NotEq => cmp::neq($lhs, $rhs)?,
        }
    }};
}

/// Compares an integer column against an integral literal, narrowing the
/// literal to the column's native type.
macro_rules! cmp_int_column {
    ($arr:expr, $scalar:expr, $op:expr, $arrow_ty:ty, $native:ty) => {{
        let col = $arr.as_primitive::<$arrow_ty>();
        let raw = $scalar.as_i128().ok_or_else(|| {
            anyhow::anyhow!(
                "cannot compare an integer column against literal {:?}",
                $scalar
            )
        })?;
        let native = <$native>::try_from(raw).map_err(|_| {
            anyhow::anyhow!(
                "literal {raw} is out of range for column type {}",
                stringify!($native)
            )
        })?;
        let scalar_arr = arrow_array::PrimitiveArray::<$arrow_ty>::new_scalar(native);
        apply_cmp!(col, &scalar_arr, $op)
    }};
}

/// Compares a scalar literal against a column, dispatching on the column's
/// Arrow type so that narrow columns (`Int32`, `Float32`, …) work with the
/// widened literals produced by `lit_*` and [`Col`].
#[allow(clippy::cast_possible_truncation)]
fn cmp_array_scalar(
    arr: &Arc<dyn Array>,
    scalar: &ScalarValue,
    op: CmpOp,
) -> anyhow::Result<BooleanArray> {
    let result = match arr.data_type() {
        DataType::Int8 => cmp_int_column!(arr, scalar, op, Int8Type, i8),
        DataType::Int16 => cmp_int_column!(arr, scalar, op, Int16Type, i16),
        DataType::Int32 => cmp_int_column!(arr, scalar, op, Int32Type, i32),
        DataType::Int64 => cmp_int_column!(arr, scalar, op, Int64Type, i64),
        DataType::UInt8 => cmp_int_column!(arr, scalar, op, UInt8Type, u8),
        DataType::UInt16 => cmp_int_column!(arr, scalar, op, UInt16Type, u16),
        DataType::UInt32 => cmp_int_column!(arr, scalar, op, UInt32Type, u32),
        DataType::UInt64 => cmp_int_column!(arr, scalar, op, UInt64Type, u64),
        DataType::Float32 => {
            let col = arr.as_primitive::<Float32Type>();
            let raw = scalar.as_f64().ok_or_else(|| {
                anyhow::anyhow!("cannot compare a float column against literal {scalar:?}")
            })?;
            let scalar_arr = arrow_array::Float32Array::new_scalar(raw as f32);
            apply_cmp!(col, &scalar_arr, op)
        }
        DataType::Float64 => {
            let col = arr.as_primitive::<Float64Type>();
            let raw = scalar.as_f64().ok_or_else(|| {
                anyhow::anyhow!("cannot compare a float column against literal {scalar:?}")
            })?;
            let scalar_arr = arrow_array::Float64Array::new_scalar(raw);
            apply_cmp!(col, &scalar_arr, op)
        }
        DataType::Utf8 => {
            let col = arr
                .as_any()
                .downcast_ref::<StringArray>()
                .ok_or_else(|| anyhow::anyhow!("expected string array"))?;
            let ScalarValue::Utf8(v) = scalar else {
                anyhow::bail!("cannot compare a string column against literal {scalar:?}");
            };
            let scalar_arr = arrow_array::StringArray::new_scalar(v);
            apply_cmp!(col, &scalar_arr, op)
        }
        DataType::Boolean => {
            let col = arr
                .as_any()
                .downcast_ref::<BooleanArray>()
                .ok_or_else(|| anyhow::anyhow!("expected boolean array"))?;
            let ScalarValue::Bool(v) = scalar else {
                anyhow::bail!("cannot compare a boolean column against literal {scalar:?}");
            };
            let scalar_arr = BooleanArray::new_scalar(*v);
            apply_cmp!(col, &scalar_arr, op)
        }
        other => anyhow::bail!("column type {other} is not comparable against a literal"),
    };
    Ok(result)
}

fn cmp_array_array(
    left: &Arc<dyn Array>,
    right: &Arc<dyn Array>,
    op: CmpOp,
) -> anyhow::Result<BooleanArray> {
    use arrow::compute::kernels::cmp;
    Ok(match op {
        CmpOp::Gt => cmp::gt(left, right)?,
        CmpOp::GtEq => cmp::gt_eq(left, right)?,
        CmpOp::Lt => cmp::lt(left, right)?,
        CmpOp::LtEq => cmp::lt_eq(left, right)?,
        CmpOp::Eq => cmp::eq(left, right)?,
        CmpOp::NotEq => cmp::neq(left, right)?,
    })
}

/// Evaluates an [`Expr`] predicate against a `RecordBatch` and returns a `BooleanArray`.
pub fn eval_predicate(expr: &Expr, batch: &RecordBatch) -> anyhow::Result<BooleanArray> {
    evaluate_to_bool(expr, batch)
}

/// Zero-copy filter operator using arrow compute kernel predicates.
///
/// Evaluates an `Expr` against the input batch columns, producing a
/// `BooleanArray` mask that is composed with any existing selection vector.
pub struct FilterExprOp<T> {
    expr: Expr,
    _phantom: PhantomData<fn(T)>,
}

impl<T> fmt::Debug for FilterExprOp<T> {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        f.debug_struct("FilterExprOp")
            .field("expr", &self.expr)
            .finish_non_exhaustive()
    }
}

impl<T> Clone for FilterExprOp<T> {
    fn clone(&self) -> Self {
        Self {
            expr: self.expr.clone(),
            _phantom: PhantomData,
        }
    }
}

impl<T: RheiSchema> FilterExprOp<T> {
    /// Creates a new filter operator with the given predicate expression.
    ///
    /// Accepts anything convertible into an [`Expr`], including a typed
    /// [`Col<bool>`].
    pub fn new(expr: impl Into<Expr>) -> Self {
        Self {
            expr: expr.into(),
            _phantom: PhantomData,
        }
    }
}

#[async_trait]
impl<T: RheiSchema> StreamFunction for FilterExprOp<T> {
    type Input = T;
    type Output = T;

    async fn process(
        &mut self,
        input: RheiBuffer<T>,
        _ctx: &mut OperatorContext,
    ) -> anyhow::Result<BufferOutput<T>> {
        if input.physical_len() == 0 {
            return Ok(BufferOutput::None);
        }

        let batch = input.as_record_batch();
        let mask = eval_predicate(&self.expr, batch)?;
        let filtered = input.and_mask(mask);

        if filtered.is_empty() {
            return Ok(BufferOutput::None);
        }
        Ok(BufferOutput::Single(filtered))
    }
}

#[cfg(test)]
#[allow(clippy::unwrap_used)]
mod tests {
    use super::*;
    use arrow_array::builder::ArrayBuilder;
    use arrow_schema::{DataType, Field, Schema};
    use std::sync::Arc;

    use crate::arrow::RheiSchema as RheiSchemaTrait;
    use crate::arrow::{OperatorContext, RheiBuffer, RheiBuilder};
    use crate::state::context::StateContext;
    use crate::state::local_backend::LocalBackend;

    struct Sensor {
        name: String,
        value: f64,
        ts: u64,
    }

    struct SensorBuilder {
        name: arrow_array::builder::StringBuilder,
        value: arrow_array::builder::PrimitiveBuilder<Float64Type>,
        ts: arrow_array::builder::PrimitiveBuilder<UInt64Type>,
    }

    struct SensorView<'a> {
        #[allow(dead_code)]
        name: &'a str,
        value: f64,
        #[allow(dead_code)]
        ts: u64,
    }

    struct SensorCols<'a> {
        #[allow(dead_code)]
        name: &'a StringArray,
        #[allow(dead_code)]
        value: &'a arrow_array::PrimitiveArray<Float64Type>,
        #[allow(dead_code)]
        ts: &'a arrow_array::PrimitiveArray<UInt64Type>,
    }

    impl crate::arrow::RheiBuilder for SensorBuilder {
        type Item = Sensor;

        fn append(&mut self, item: Sensor) {
            self.name.append_value(&item.name);
            self.value.append_value(item.value);
            self.ts.append_value(item.ts);
        }

        fn append_null(&mut self) {
            self.name.append_null();
            self.value.append_null();
            self.ts.append_null();
        }

        fn len(&self) -> usize {
            self.name.len()
        }

        fn finish(mut self) -> RecordBatch {
            RecordBatch::try_new(
                Sensor::arrow_schema(),
                vec![
                    Arc::new(self.name.finish()),
                    Arc::new(self.value.finish()),
                    Arc::new(self.ts.finish()),
                ],
            )
            .unwrap()
        }
    }

    impl RheiSchemaTrait for Sensor {
        type Builder = SensorBuilder;
        type View<'a> = SensorView<'a>;
        type Columns<'a> = SensorCols<'a>;

        fn arrow_schema() -> Arc<Schema> {
            Arc::new(Schema::new(vec![
                Field::new("name", DataType::Utf8, false),
                Field::new("value", DataType::Float64, false),
                Field::new("ts", DataType::UInt64, false),
            ]))
        }

        fn builder(capacity: usize) -> Self::Builder {
            SensorBuilder {
                name: arrow_array::builder::StringBuilder::with_capacity(capacity, capacity * 8),
                value: arrow_array::builder::PrimitiveBuilder::with_capacity(capacity),
                ts: arrow_array::builder::PrimitiveBuilder::with_capacity(capacity),
            }
        }

        fn view(batch: &RecordBatch, index: usize) -> Self::View<'_> {
            SensorView {
                name: batch.column(0).as_string::<i32>().value(index),
                value: batch.column(1).as_primitive::<Float64Type>().value(index),
                ts: batch.column(2).as_primitive::<UInt64Type>().value(index),
            }
        }

        fn columns(batch: &RecordBatch) -> Self::Columns<'_> {
            SensorCols {
                name: batch.column(0).as_string::<i32>(),
                value: batch.column(1).as_primitive::<Float64Type>(),
                ts: batch.column(2).as_primitive::<UInt64Type>(),
            }
        }
    }

    fn test_ctx() -> OperatorContext {
        let dir = tempfile::tempdir().unwrap();
        let backend = LocalBackend::new(dir.path().join("state.json"), None).unwrap();
        OperatorContext::new(StateContext::new(Box::new(backend)))
    }

    fn make_sensors() -> RheiBuffer<Sensor> {
        let mut builder = Sensor::builder(5);
        builder.append(Sensor {
            name: "a".into(),
            value: 10.0,
            ts: 1,
        });
        builder.append(Sensor {
            name: "b".into(),
            value: 25.0,
            ts: 2,
        });
        builder.append(Sensor {
            name: "a".into(),
            value: 30.0,
            ts: 3,
        });
        builder.append(Sensor {
            name: "c".into(),
            value: 5.0,
            ts: 4,
        });
        builder.append(Sensor {
            name: "b".into(),
            value: 50.0,
            ts: 5,
        });
        RheiBuffer::from_builder(builder)
    }

    #[tokio::test]
    async fn filter_gt_scalar() {
        let mut ctx = test_ctx();
        let mut op = FilterExprOp::<Sensor>::new(col("value").gt(lit_f64(20.0)));

        let input = make_sensors();
        let result = op.process(input, &mut ctx).await.unwrap();
        let BufferOutput::Single(buf) = result else {
            panic!("expected Single");
        };
        assert_eq!(buf.len(), 3);
        let values: Vec<f64> = buf.iter().map(|v| v.value).collect();
        assert_eq!(values, vec![25.0, 30.0, 50.0]);
    }

    #[tokio::test]
    async fn filter_eq_string() {
        let mut ctx = test_ctx();
        let mut op = FilterExprOp::<Sensor>::new(col("name").eq(lit_str("a")));

        let input = make_sensors();
        let result = op.process(input, &mut ctx).await.unwrap();
        let BufferOutput::Single(buf) = result else {
            panic!("expected Single");
        };
        assert_eq!(buf.len(), 2);
    }

    #[tokio::test]
    async fn filter_and_compound() {
        let mut ctx = test_ctx();
        let expr = col("value").gt(lit_f64(10.0)).and(col("ts").lt(lit_u64(5)));
        let mut op = FilterExprOp::<Sensor>::new(expr);

        let input = make_sensors();
        let result = op.process(input, &mut ctx).await.unwrap();
        let BufferOutput::Single(buf) = result else {
            panic!("expected Single");
        };
        // value > 10 AND ts < 5 → (25.0, ts=2), (30.0, ts=3)
        assert_eq!(buf.len(), 2);
    }

    #[tokio::test]
    async fn filter_or() {
        let mut ctx = test_ctx();
        let expr = col("value")
            .lt(lit_f64(10.0))
            .or(col("value").gt(lit_f64(40.0)));
        let mut op = FilterExprOp::<Sensor>::new(expr);

        let input = make_sensors();
        let result = op.process(input, &mut ctx).await.unwrap();
        let BufferOutput::Single(buf) = result else {
            panic!("expected Single");
        };
        // value < 10 → (5.0), value > 40 → (50.0)
        assert_eq!(buf.len(), 2);
    }

    #[tokio::test]
    async fn filter_not() {
        let mut ctx = test_ctx();
        let mut op = FilterExprOp::<Sensor>::new(col("name").eq(lit_str("a")).negate());

        let input = make_sensors();
        let result = op.process(input, &mut ctx).await.unwrap();
        let BufferOutput::Single(buf) = result else {
            panic!("expected Single");
        };
        // not(name == "a") → 3 rows (b, c, b)
        assert_eq!(buf.len(), 3);
    }

    #[tokio::test]
    async fn filter_all_excluded_returns_none() {
        let mut ctx = test_ctx();
        let mut op = FilterExprOp::<Sensor>::new(col("value").gt(lit_f64(1000.0)));

        let input = make_sensors();
        let result = op.process(input, &mut ctx).await.unwrap();
        assert!(result.is_empty());
    }

    #[tokio::test]
    async fn filter_empty_input() {
        let mut ctx = test_ctx();
        let mut op = FilterExprOp::<Sensor>::new(col("value").gt(lit_f64(0.0)));

        let input: RheiBuffer<Sensor> = RheiBuffer::from_builder(Sensor::builder(0));
        let result = op.process(input, &mut ctx).await.unwrap();
        assert!(result.is_empty());
    }

    // ── Typed column handles and narrow column types ──────────────────

    /// Batch with one narrow column of each family, plus a nullable column.
    fn narrow_batch() -> RecordBatch {
        let schema = Arc::new(Schema::new(vec![
            Field::new("small_int", DataType::Int32, false),
            Field::new("small_uint", DataType::UInt16, false),
            Field::new("small_float", DataType::Float32, false),
            Field::new("maybe", DataType::Int64, true),
        ]));
        RecordBatch::try_new(
            schema,
            vec![
                Arc::new(arrow_array::Int32Array::from(vec![1, 5, 9])),
                Arc::new(arrow_array::UInt16Array::from(vec![10_u16, 50, 90])),
                Arc::new(arrow_array::Float32Array::from(vec![1.5_f32, 5.5, 9.5])),
                Arc::new(arrow_array::Int64Array::from(vec![Some(1), None, Some(3)])),
            ],
        )
        .unwrap()
    }

    fn matches(expr: &Expr, batch: &RecordBatch) -> Vec<bool> {
        let mask = eval_predicate(expr, batch).unwrap();
        (0..batch.num_rows()).map(|i| mask.value(i)).collect()
    }

    #[test]
    fn typed_col_compares_narrow_int_column() {
        let batch = narrow_batch();
        let small_int: Col<i32> = Col::new("small_int");
        assert_eq!(matches(&small_int.gt(4), &batch), vec![false, true, true]);
        assert_eq!(
            matches(&small_int.lt_eq(5), &batch),
            vec![true, true, false]
        );
    }

    #[test]
    fn typed_col_compares_narrow_uint_and_float_columns() {
        let batch = narrow_batch();
        let small_uint: Col<u16> = Col::new("small_uint");
        let small_float: Col<f32> = Col::new("small_float");
        assert_eq!(
            matches(&small_uint.gt_eq(50_u16), &batch),
            vec![false, true, true]
        );
        assert_eq!(
            matches(&small_float.lt(5.5_f32), &batch),
            vec![true, false, false]
        );
    }

    #[test]
    fn untyped_literals_also_narrow_to_the_column_type() {
        // `lit_i64` against an Int32 column used to panic on downcast.
        let batch = narrow_batch();
        assert_eq!(
            matches(&col("small_int").gt(lit_i64(4)), &batch),
            vec![false, true, true]
        );
    }

    #[test]
    fn out_of_range_literal_is_an_error_not_a_panic() {
        let batch = narrow_batch();
        let err = eval_predicate(&col("small_int").gt(lit_i64(i64::MAX)), &batch).unwrap_err();
        assert!(
            err.to_string().contains("out of range"),
            "unexpected error: {err}"
        );
    }

    #[test]
    fn mismatched_literal_kind_is_an_error() {
        let batch = narrow_batch();
        let err = eval_predicate(&col("small_int").eq(lit_str("nope")), &batch).unwrap_err();
        assert!(
            err.to_string().contains("integer column"),
            "unexpected error: {err}"
        );
    }

    #[test]
    fn null_predicates() {
        let batch = narrow_batch();
        let maybe: Col<i64> = Col::new("maybe");
        assert_eq!(matches(&maybe.is_null(), &batch), vec![false, true, false]);
        assert_eq!(
            matches(&maybe.is_not_null(), &batch),
            vec![true, false, true]
        );
    }

    #[test]
    fn null_rows_do_not_match_comparisons() {
        let batch = narrow_batch();
        let maybe: Col<i64> = Col::new("maybe");
        assert_eq!(matches(&maybe.gt(0), &batch), vec![true, false, true]);
    }

    #[test]
    fn between_is_inclusive() {
        let batch = narrow_batch();
        let small_int: Col<i32> = Col::new("small_int");
        assert_eq!(
            matches(&small_int.between(1, 5), &batch),
            vec![true, true, false]
        );
    }

    #[test]
    fn is_in_matches_any_listed_value() {
        let batch = narrow_batch();
        let small_int: Col<i32> = Col::new("small_int");
        assert_eq!(
            matches(&small_int.is_in([1, 9]), &batch),
            vec![true, false, true]
        );
    }

    #[test]
    fn is_in_with_no_values_matches_nothing() {
        let batch = narrow_batch();
        let small_int: Col<i32> = Col::new("small_int");
        assert_eq!(
            matches(&small_int.is_in(Vec::<i32>::new()), &batch),
            vec![false, false, false]
        );
    }

    #[test]
    fn string_col_accepts_borrowed_literals() {
        let mut builder = Sensor::builder(2);
        builder.append(Sensor {
            name: "a".into(),
            value: 1.0,
            ts: 1,
        });
        builder.append(Sensor {
            name: "b".into(),
            value: 2.0,
            ts: 2,
        });
        let buf: RheiBuffer<Sensor> = RheiBuffer::from_builder(builder);
        let name: Col<String> = Col::new("name");
        assert_eq!(
            matches(&name.eq("a"), buf.as_record_batch()),
            vec![true, false]
        );
    }

    #[test]
    fn bool_col_is_a_predicate_on_its_own() {
        let schema = Arc::new(Schema::new(vec![Field::new(
            "flag",
            DataType::Boolean,
            false,
        )]));
        let batch = RecordBatch::try_new(
            schema,
            vec![Arc::new(BooleanArray::from(vec![true, false, true]))],
        )
        .unwrap();

        let flag: Col<bool> = Col::new("flag");
        assert_eq!(matches(&flag.into(), &batch), vec![true, false, true]);

        // `FilterExprOp::new` takes the handle without an explicit `.expr()`.
        let op = FilterExprOp::<Sensor>::new(flag);
        assert!(format!("{op:?}").contains("flag"));
    }

    #[test]
    fn col_exposes_its_name() {
        let name: Col<String> = Col::new("name");
        assert_eq!(name.name(), "name");
        assert!(matches!(Expr::from(name), Expr::Column(n) if n == "name"));
    }
}
